src/Trez/LogicielTrezBundle/Entity/DeclarationTva.php
<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * DeclarationTva
 * @UniqueEntity(fields={"date"}, message="Une déclaration existe déjà pour cette date")
 */
class DeclarationTva
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $date;

    /**
     * @var integer
     */
    private $solde_precedent;

    /**
     * @var integer
     */
    private $solde_final;

    /**
     * @var string
     */
    private $feuille;

    /**
     * @var string
     */
    private $commentaire;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $factures;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->factures = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return DeclarationTva
     */
    public function setDate($date)
    {
        $this->date = $date;
    
        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set solde_precedent
     *
     * @param integer $soldePrecedent
     * @return DeclarationTva
     */
    public function setSoldePrecedent($soldePrecedent)
    {
        $this->solde_precedent = $soldePrecedent;
    
        return $this;
    }

    /**
     * Get solde_precedent
     *
     * @return integer 
     */
    public function getSoldePrecedent()
    {
        return $this->solde_precedent;
    }

    /**
     * Set solde_final
     *
     * @param integer $soldeFinal
     * @return DeclarationTva
     */
    public function setSoldeFinal($soldeFinal)
    {
        $this->solde_final = $soldeFinal;

        return $this;
    }

    /**
     * Get solde_final
     *
     * @return integer
     */
    public function getSoldeFinal()
    {
        return $this->solde_final;
    }

    /**
     * Set feuille
     *
     * @param string $feuille
     * @return DeclarationTva
     */
    public function setFeuille($feuille)
    {
        $this->feuille = $feuille;
    
        return $this;
    }

    /**
     * Get feuille
     *
     * @return string 
     */
    public function getFeuille()
    {
        return $this->feuille;
    }

    /**
     * Set commentaire
     *
     * @param string $commentaire
     * @return DeclarationTva
     */
    public function setCommentaire($commentaire)
    {
        $this->commentaire = $commentaire;
    
        return $this;
    }

    /**
     * Get commentaire
     *
     * @return string 
     */
    public function getCommentaire()
    {
        return $this->commentaire;
    }

    /**
     * Add factures
     *
     * @param \Trez\LogicielTrezBundle\Entity\Facture $factures
     * @return DeclarationTva
     */
    public function addFacture(\Trez\LogicielTrezBundle\Entity\Facture $factures)
    {
        $this->factures[] = $factures;
    
        return $this;
    }

    /**
     * Remove factures
     *
     * @param \Trez\LogicielTrezBundle\Entity\Facture $factures
     */
    public function removeFacture(\Trez\LogicielTrezBundle\Entity\Facture $factures)
    {
        $this->factures->removeElement($factures);
    }

    /**
     * Get factures
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFactures()
    {
        return $this->factures;
    }

    /**
     * Renvoie la date en string pour les filtres select
     *
     * @return String
     */
    public function __toString()
    {
        return $this->date->format('Y-m');
    }
}

src/Trez/LogicielTrezBundle/Entity/Facture.php
<?php

namespace Trez\LogicielTrezBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\ExecutionContext;
use Symfony\Component\Validator\Constraints as Assert;
use Trez\LogicielTrezBundle\Validator\Constraints as TrezAssert;

/**
 * Trez\LogicielTrezBundle\Entity\Facture
 *  @Assert\Callback(methods={"isUnderTotal"}, groups={"under_total"})
 *  @Assert\Callback(methods={"isNotNull"})
 *  @Assert\Callback(methods={"isTvasCorrect"})
 *  @TrezAssert\NumeroUnique
 */
class Facture
{
    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var integer $numero
     * @Assert\NotBlank()
     * @Assert\Range(
     *  min = "1",
     *  minMessage = "Le numéro ne peut pas être inférieur à 1"
     * )
     */
    private $numero;

    /**
     * @var string $objet
     * @Assert\NotBlank()
     */
    private $objet;

    /**
     * @var float $montant
     * @Assert\NotBlank()
     */
    private $montant;

    /**
     * @var \DateTime $date
     */
    private $date;

    /**
     * @var \DateTime $date_paiement
     */
    private $date_paiement;

    /**
     * @var string $commentaire
     */
    private $commentaire;

    /**
     * @var string $ref_paiement
     */
    private $ref_paiement;

    /**
     * @var Trez\LogicielTrezBundle\Entity\Ligne
     * @Assert\Valid
     */
    private $ligne;

    /**
     * @var Trez\LogicielTrezBundle\Entity\Tiers
     */
    private $tiers;

    /**
     * @var Trez\LogicielTrezBundle\Entity\MethodePaiement
     */
    private $methodePaiement;

    /**
     * @var Trez\LogicielTrezBundle\Entity\TypeFacture
     */
    private $typeFacture;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $tvas;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set numero
     *
     * @param integer $numero
     * @return Facture
     */
    public function setNumero($numero)
    {
        $this->numero = $numero;
    
        return $this;
    }

    /**
     * Get numero
     *
     * @return integer 
     */
    public function getNumero()
    {
        return $this->numero;
    }

    /**
     * Set objet
     *
     * @param string $objet
     * @return Facture
     */
    public function setObjet($objet)
    {
        $this->objet = $objet;
    
        return $this;
    }

    /**
     * Get objet
     *
     * @return string 
     */
    public function getObjet()
    {
        return $this->objet;
    }

    /**
     * Set montant
     *
     * @param float $montant
     * @return Facture
     */
    public function setMontant($montant)
    {
        $this->montant = $montant;
    
        return $this;
    }

    /**
     * Get montant
     *
     * @return float 
     */
    public function getMontant()
    {
        return $this->montant;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Facture
     */
    public function setDate($date)
    {
        $this->date = $date;
    
        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set date_paiement
     *
     * @param \DateTime $datePaiement
     * @return Facture
     */
    public function setDatePaiement($datePaiement)
    {
        $this->date_paiement = $datePaiement;
    
        return $this;
    }

    /**
     * Get date_paiement
     *
     * @return \DateTime 
     */
    public function getDatePaiement()
    {
        return $this->date_paiement;
    }

    /**
     * Set commentaire
     *
     * @param string $commentaire
     * @return Facture
     */
    public function setCommentaire($commentaire)
    {
        $this->commentaire = $commentaire;
    
        return $this;
    }

    /**
     * Get commentaire
     *
     * @return string 
     */
    public function getCommentaire()
    {
        return $this->commentaire;
    }

    /**
     * Set ref_paiement
     *
     * @param string $refPaiement
     * @return Facture
     */
    public function setRefPaiement($refPaiement)
    {
        $this->ref_paiement = $refPaiement;
    
        return $this;
    }

    /**
     * Get ref_paiement
     *
     * @return string 
     */
    public function getRefPaiement()
    {
        return $this->ref_paiement;
    }

    /**
     * Set ligne
     *
     * @param Trez\LogicielTrezBundle\Entity\Ligne $ligne
     * @return Facture
     */
    public function setLigne(\Trez\LogicielTrezBundle\Entity\Ligne $ligne = null)
    {
        $this->ligne = $ligne;
    
        return $this;
    }

    /**
     * Get ligne
     *
     * @return Trez\LogicielTrezBundle\Entity\Ligne 
     */
    public function getLigne()
    {
        return $this->ligne;
    }

    /**
     * Set tiers
     *
     * @param Trez\LogicielTrezBundle\Entity\Tiers $tiers
     * @return Facture
     */
    public function setTiers(\Trez\LogicielTrezBundle\Entity\Tiers $tiers = null)
    {
        $this->tiers = $tiers;
    
        return $this;
    }

    /**
     * Get tiers
     *
     * @return Trez\LogicielTrezBundle\Entity\Tiers 
     */
    public function getTiers()
    {
        return $this->tiers;
    }

    /**
     * Set methodePaiement
     *
     * @param Trez\LogicielTrezBundle\Entity\MethodePaiement $methodePaiement
     * @return Facture
     */
    public function setMethodePaiement(\Trez\LogicielTrezBundle\Entity\MethodePaiement $methodePaiement = null)
    {
        $this->methodePaiement = $methodePaiement;
    
        return $this;
    }

    /**
     * Get methodePaiement
     *
     * @return Trez\LogicielTrezBundle\Entity\MethodePaiement 
     */
    public function getMethodePaiement()
    {
        return $this->methodePaiement;
    }

    /**
     * Set typeFacture
     *
     * @param Trez\LogicielTrezBundle\Entity\TypeFacture $typeFacture
     * @return Facture
     */
    public function setTypeFacture(\Trez\LogicielTrezBundle\Entity\TypeFacture $typeFacture = null)
    {
        $this->typeFacture = $typeFacture;
    
        return $this;
    }

    /**
     * Get typeFacture
     *
     * @return Trez\LogicielTrezBundle\Entity\TypeFacture 
     */
    public function getTypeFacture()
    {
        return $this->typeFacture;
    }

    /*
     * Check if we don't exceed ligne total (debit or credit)
     */
    public function isUnderTotal(ExecutionContext $context)
    {
        $this->ligne->getFreeTotal($credit, $debit, $this->id);

        $depassement = ($this->typeFacture->getSens() === true) ? $this->montant-$credit : $this->montant-$debit;

        if ($depassement > 0.001) { // compare with an epsilon!
            $context->addViolationAt('montant',
                'Cette facture dépasse du total de la ligne de %montant% €',
                array('%montant%' => round($depassement, 2)),
                null);
        }
    }

    /*
     * Check if montant is not null
     */
    public function isNotNull(ExecutionContext $context)
    {
        if ($this->montant === 0.0) {
            $context->addViolationAt('montant', 'Une facture ne peut pas avoir un montant nul', array(), null);
        }
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->tvas = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add tvas
     *
     * @param \Trez\LogicielTrezBundle\Entity\Tva $tvas
     * @return Facture
     */
    public function addTva(\Trez\LogicielTrezBundle\Entity\Tva $tvas)
    {
        $tvas->setFacture($this); // added because we're the inverse side

        $this->tvas[] = $tvas;
    
        return $this;
    }

    /**
     * Remove tvas
     *
     * @param \Trez\LogicielTrezBundle\Entity\Tva $tvas
     */
    public function removeTva(\Trez\LogicielTrezBundle\Entity\Tva $tvas)
    {
        $this->tvas->removeElement($tvas);
    }

    /**
     * Get tvas
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTvas()
    {
        return $this->tvas;
    }

    /*
     * Check if parent is verrouille, thus throw an exception
     */
    public function checkVerrouille()
    {
        $this->ligne->checkVerrouille();
    }

    /*
     * Get the montant TTC, including TVA
     */
    public function getMontantTtc()
    {
        $montant_ttc = $this->montant;

        foreach ($this->tvas as $tva) {
            $montant_ttc += $tva->getMontantTva();
        }

        return $montant_ttc;
    }

    /*
     * Check if no TVA is missing
     */
    public function isTvasCorrect(ExecutionContext $context)
    {
        $montant_ht = 0;

        foreach ($this->tvas as $tva) {
            $montant_ht += $tva->getMontantHt();
        }

        if (abs($this->montant - $montant_ht) > 0.001) { // floats -> epsilon!
            $context->addViolationAt('tvas', 'La somme des montants HT doit être égale au montant de la facture');
        }
    }

    /*
     * Some getter to simulate properties
     */
    public function getExercice()
    {
        return $this->ligne->getSousCategorie()->getCategorie()->getBudget()->getExercice();
    }
    /**
     * @var \Trez\LogicielTrezBundle\Entity\DeclarationTva
     */
    private $declarationTva;


    /**
     * Set declarationTva
     *
     * @param \Trez\LogicielTrezBundle\Entity\DeclarationTva $declarationTva
     * @return Facture
     */
    public function setDeclarationTva(\Trez\LogicielTrezBundle\Entity\DeclarationTva $declarationTva = null)
    {
        $this->declarationTva = $declarationTva;
    
        return $this;
    }

    /**
     * Get declarationTva
     *
     * @return \Trez\LogicielTrezBundle\Entity\DeclarationTva 
     */
    public function getDeclarationTva()
    {
        return $this->declarationTva;
    }
    /**
     * @var \DateTime
     */
    private $date_ecriture;


    /**

src/Trez/LogicielTrezBundle/Resources/views/DeclarationTva/create.html.twig
{%  extends 'TrezLogicielTrezBundle::layout.html.twig' %}
{% import 'TrezLogicielTrezBundle:Utils:forms.html.twig' as forms %}

{% block body %}
    <h1>Créer une déclaration de TVA</h1>

    <form class="form-horizontal" action="{{ path('declaration_tva_create') }}" {{ form_enctype(form) }} method="post">
        <div>{{ form_errors(form) }}</div>

        <fieldset>
            {{ forms.field(form.date, 'Date', {'class': 'date-selects'}) }}
        </fieldset>

        {{ form_rest(form) }}

        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Valider">&nbsp;
            <a href="{{ path('declaration_tva_index') }}" class="btn">Annuler</a>
        </div>
    </form>

    <script type="text/javascript">
        // we set some values in useless selects and hide them
        $('#trez_logicieltrezbundle_declarationtvadate_date_day').val(1).hide();

        // pre-set with next date
        $('#trez_logicieltrezbundle_declarationtvadate_date_month').val({{ date_next|date('m') }});
        $('#trez_logicieltrezbundle_declarationtvadate_date_year').val({{ date_next|date('Y') }});
    </script>
{% endblock %}

src/Trez/LogicielTrezBundle/Resources/views/DeclarationTva/edit.html.twig
{%  extends 'TrezLogicielTrezBundle::layout.html.twig' %}
{% import 'TrezLogicielTrezBundle:Utils:forms.html.twig' as forms %}

{% block body %}
    <h1>Éditer une déclaration de TVA</h1>

    <form class="form-horizontal" action="{{ path('declaration_tva_edit', {id: declaration_tva.id}) }}" {{ form_enctype(form) }} method="post">
        <div>{{ form_errors(form) }}</div>

        <fieldset>
            {{ forms.field(form.date, 'Date', {'class': 'date-fix'}) }}
            {{ forms.field(form.solde_precedent, 'Solde précédent', {'class': 'input-small'}) }}
            {{ forms.field(form.solde_final, 'Solde final', {'class': 'input-small'}) }}
            {{ forms.field(form.commentaire, 'Commentaire', {'class': 'input-xlarge'}) }}
        </fieldset>

        {{ form_rest(form) }}

        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Valider">&nbsp;
            <a href="{{ path('declaration_tva_index') }}" class="btn">Annuler</a>
        </div>
    </form>
{% endblock %}

src/Trez/LogicielTrezBundle/Resources/views/DeclarationTva/list.html.twig
{%  extends 'TrezLogicielTrezBundle::layout.html.twig' %}
{% import 'TrezLogicielTrezBundle:Utils:forms.html.twig' as forms %}

{% block body %}
    <h1>Liste des déclarations de TVA</h1>

    <table class="table table-stripped table-hover">
        <thead>
        <tr>
            <th>Période</th>
            <th>Solde précédent</th>
            <th>Solde final</th>
            <th width="50"></th>
        </tr>
        </thead>
        <tbody>
        {% for declaration in declarations %}
            <tr>
                <td>{{ declaration.date|date('m/Y') }}</td>
                <td>{{ declaration.soldePrecedent|excel_format }}</td>
                <td>{{ declaration.soldeFinal|excel_format }}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-small" href="{{ path('declaration_tva_edit', {'id': declaration.id}) }}" title="&Eacute;diter"><i class="icon-pencil icon-large icon-large"></i></a>
                        <a class="btn btn-small"
                           href="{{ path('declaration_tva_delete', {'id': declaration.id}) }}"
                           onclick="return window.confirm('Êtes-vous sur de vouloir supprimer la déclaration de TVA du {{ declaration.date|date('m/Y') }} ?');"
                           title="Supprimer"><i class="icon-remove icon-large icon-large"></i></a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div>
        <a href="{{ path('declaration_tva_create') }}" class='btn btn-primary'>
            <i class="icon-plus"></i> Créer une déclaration de TVA
        </a>
    </div>
{% endblock %}

src/Trez/LogicielTrezBundle/Resources/views/DeclarationTva/list_factures.html.twig
{% extends 'TrezLogicielTrezBundle::layout.html.twig' %}
{% import 'TrezLogicielTrezBundle:Utils:forms.html.twig' as forms %}

{#
    customize how checkboxes are displayed - add label around input
    we override base template:
    https://github.com/symfony/symfony/blob/2.2/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig
#}
{% form_theme form _self %}
{% block choice_widget_expanded %}
    {% import 'TrezLogicielTrezBundle:Utils:utils.html.twig' as utils %}
    {% spaceless %}
        <div {{ block('widget_container_attributes') }}>
            {% for child in form %}
                {% set facture = form.parent.children.factures.vars.choices[child.vars.value].data %}
                <tr {% if facture.datePaiement < date('first day of this month') %}class="error"{% endif %}>
                    <td>{{ form_widget(child) }}</td>
                    <td>{{ facture.typeFacture.abr ~ facture.ligne.sousCategorie.categorie.budget.exercice.prefixeFactures ~ utils.untrim_number(facture.numero, 3)|trim }}</td>
                    <td>
                        <label for="{{ child.vars.id }}">{{ facture.objet }}</label>
                    </td>
                    <td>{{ facture.date|date("d/m/Y") }}</td>
                    <td>{{ facture.montant|excel_format }}</td>
                    <td>
                        <a class="btn btn-small" href="{{ path('facture_edit', {'ligne_id': facture.ligne.id, 'id': facture.id}) }}" title="&Eacute;diter"><i class="icon-pencil icon-large"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </div>
    {% endspaceless %}
{% endblock choice_widget_expanded %}
{% block checkbox_widget %}
    {% spaceless %}
        <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} class="no-margin" />
    {% endspaceless %}
{% endblock checkbox_widget %}

{% block body %}
    <h1 class="margin-bottom-20">Sélectionnez les factures pour la déclaration du mois {{ declaration_tva.date|date('m/y') }}</h1>

    <form class="form-horizontal" action="{{ path('declaration_tva_list_factures', {id: declaration_tva.id }) }}" {{ form_enctype(form) }} method="post">
        <div>{{ form_errors(form) }}</div>

        <div class="{{ form_errors(form.factures) ? 'error' : '' }}">
            <table class="table table-stripped table-hover">
                <thead>
                    <tr>
                        <th width="30"></th>
                        <th>Numéro</th>
                        <th>Objet</th>
                        <th>Date</th>
                        <th>Montant</th>
                        <td width="30"></td>
                    </tr>
                </thead>
                <tbody>
                    {{ form_widget(form.factures) }}
                </tbody>
            </table>
            <span class="help-inline">{{ form_errors(form.factures) }}</span>
        </div>

        {{ form_rest(form) }}

        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Valider">&nbsp;
            <a href="{{ path('declaration_tva_index') }}" class="btn">Annuler</a>
        </div>
    </form>
{% endblock %}